name = "app"
version = "1.0.0"
target = "javascript"

[tools.lustre.bin]
bun = "system"

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
lustre = ">= 5.5.2 and < 6.0.0"
gleam_time = ">= 1.7.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
lustre_dev_tools = ">= 2.3.4 and < 3.0.0"
